### ISSUE TITLE
Not accurate at all

### ISSUE THREAD

**Issue by wen0320** [markstent/audio-similarity#1]
I tried to calculate the similarity between two different sentences spoken by the same person, using just 'swass,' and the score was 0.567. However, when I tested with audio from two different people, I found that the 'swass' score was always around 0.632. Therefore, I have serious doubts about the accuracy of your method.

**Comment by markstent** [comment]
It uses a series of similarity metrics taken from the audio themselves and
then applies subjective weights to it… so it will all depend how you set it
up.

It is a bit outdated now with new technology out there though…. I did this
a couple of years back!
